
GET http://localhost:5000/api/categories

###

GET http://localhost:5000/api/categories/fde6577a-f327-4210-be81-19305b4f403a

###

POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "name": "restaurant", 
}

###

PUT http://localhost:5000/api/categories/e28c1416-4d14-41fd-972a-95f706891523
Content-Type: application/json

{
  "name": "Bar"
}

###

DELETE http://localhost:5000/api/categories/3ec194ab-80f9-4c46-98f8-0428e110b175
