GET http://localhost:5000/api/categories

###

GET http://localhost:5000/api/categories/cbcd43fe-fed9-41c4-a9e9-5761b7b7206e

###

POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "name": "bar", 
  "image": ""
}

###

PUT http://localhost:5000/api/categories/b51ee200-61e6-482f-9ef6-a9936b133049
Content-Type: application/json

{
  "name": "boîte de nuit", 
  "image": ""
}

###

DELETE http://localhost:5000/api/categories/a513866d-b529-4166-8206-44d27f828910
