GET http://localhost:5000/api/cities

###

GET http://localhost:5000/api/cities/2b0e7f15-6609-49b9-acc5-134dec517677

###

POST http://localhost:5000/api/cities
Content-Type: application/json

{
  "latitude": 40.5,
  "longitude": 40.7,
  "name": "Marmande",
  "image": "",
  "user_admin_city": "ae720191-dac3-4170-b653-b1df92377919"
}

###


PUT http://localhost:5000/api/cities/2b0e7f15-6609-49b9-acc5-134dec517677
Content-Type: application/json

{
  "user_admin_city": "ae720191-dac3-4170-b653-b1df92377919"
}

###

DELETE http://localhost:5000/api/cities/354738cc-49fd-4489-a497-6e765c136c37
