GET http://localhost:5000/api/poi

###

GET http://localhost:5000/api/poi/2e91db0d-9fb1-44ae-a26c-8c1f0decc182

###

POST http://localhost:5000/api/poi
Content-Type: application/json

{
  "name": "Point d'intérêt incroyable",
    "latitude": 40.5,
  "longitude": 40.5,
  "description": "Lorem ipsum",
  "address": "Lorem ipsum",
  "image": "Lorem ipsum",
  "is_accepted": true,
  "category": null, 
  "city": null, 
  "user": null
}

###

PUT http://localhost:5000/api/poi/302e23b7-5767-4262-8c30-b8cf0094fbce
Content-Type: application/json

{
  "user": "161b91c0-a21c-4dc8-ad86-9ebd2ebbe09e"
}

###

DELETE http://localhost:5000/api/poi/2e91db0d-9fb1-44ae-a26c-8c1f0decc182
