GET http://localhost:5000/api/poi

###

GET http://localhost:5000/api/poi/2e91db0d-9fb1-44ae-a26c-8c1f0decc182

###

POST http://localhost:5000/api/poi
Content-Type: application/json

{
  "name": "Point d'intérêt incroyable",
  "coordinates": "(45.75, 1.44)",
  "description": "Lorem ipsum",
  "address": "Lorem ipsum",
  "image": "Lorem ipsum",
  "is_accepted": true,
  "categoryIdId": null, 
  "cityIdId": null, 
  "userIdId": null
}

###

PUT http://localhost:5000/api/poi/754a2735-f923-41b1-9ec1-217245428702
Content-Type: application/json

{
  "name": "Point d'intérêt de fou",
  "coordinates": "(45.75,1.44)",
  "description": "Lorem ipsum",
  "address": "Lorem ipsum",
  "image": "Lorem ipsum",
  "is_accepted": true, 
}

###

DELETE http://localhost:5000/api/poi/2e91db0d-9fb1-44ae-a26c-8c1f0decc182
